# Generated by Django 3.0.3 on 2023-02-07 11:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_picture', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=1000)),
                ('room_number', models.CharField(max_length=100)),
                ('subjects_taught', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Telugu'), (2, 'Hindhi'), (3, 'English'), (4, 'Mathematics'), (5, 'Social'), (6, 'Science')], max_length=11)),
            ],
            options={
                'db_table': 'teachers_data',
            },
        ),
    ]
