# Generated by Django 3.0.3 on 2023-02-07 11:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_auto_20230207_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersdata',
            name='subjects_taught',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Telugu', 'Telugu'), ('Hindhi', 'Hindhi'), ('English', 'English'), ('Mathematics', 'Mathematics'), ('Social', 'Social'), ('Science', 'Science')], max_length=48),
        ),
    ]
